# worflow for building the back end

name: "Java backend CI" # the name of the job when ran

# events that will trigger this workflow to run
on: 
  push:
    branches: [ "main", "develop"]
    paths: # only trigger if changes in this paths
      - 'backend/**'
  pull_request:
    branches: [ "main", "develop"]
    paths:
      - 'backend/**'

env:
  java_version: 17
  java_distribution: temurin
defaults:
  run:
      working-directory: ./backend
# run in parallel by default
# can be multiple jobs
# cannot share machines between jobs so either steps or need to check out in each job
jobs:
    build: # first job
        runs-on: ubuntu-latest # the "worker node" where it's going to be build
        steps:
            - name: Check out code
              uses: actions/checkout@v4.1.7 # action

            - name: Set up jdk ${{ env.java_version }}
              uses: actions/setup-java@v4
              with:
                java-version: ${{ env.java_version }}
                distribution: ${{ env.java_distribution }}

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
            
            - name: Build with Gradle
              run: ./gradlew build
