# worflow for building the front end

name: "React frotend CI" # the name of the job when ran

# events that will trigger this workflow to run
on: 
  push:
    branches: [ "main", "develop"]
    paths: # only trigger if changes in this paths
      - 'frontend/**'
  pull_request:
    branches: [ "main", "develop"]
    paths:
      - 'frontend/**'


# run in parallel by default
# can be multiple jobs
jobs:
    build: # first job
        runs-on: ubuntu-latest # the "worker node" where it's going to be build
        defaults: # default settings that will apply to all steps in the job
            run:
                working-directory: ./frontend
        strategy:
            matrix:
                node-version: [22.x] # specify a version, will take the latest otherwise
        steps:
            - name: Check out code
              uses: actions/checkout@v4.1.7 # action

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4.0.3 # action
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'npm'
                cache-dependency-path: './frontend/package-lock.json'
            
            - name: Run npm clean install
              run: npm ci

              # can have or not a name
            - run: npm run build --if-present
